name: Check for infrastructure drift

on:
  schedule:
    - cron:  "0 11 * * *"

jobs:
  check_drift:
    runs-on: ubuntu-latest
    name: Check for drift of example terraform configuration
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          ## the following creates an ARN based on the values entered into github secrets
          #role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE }}
          role-session-name: myGitHubActions
      - name: Check for drift
        uses: dflook/terraform-check@v1
        